import Head from 'next/head'
import InfiniteScroll from "react-infinite-scroll-component";
import {useState} from "react";
import Preloader from "@/components/Preloader";
import Post from "@/components/Post";



export async function getServerSideProps () {
    const res = await fetch(`http://localhost:7000/api/gallery?limit=12&page=1`)
    const data = await res.json()
    return {
        props: {
            data: data
        }
    }
}

export default function Home({data}) {
    const [posts,setPosts] = useState(data.rows)
    let [currentPage,setCurrentPage] = useState(1)
    const [hasMore,setHasMore] = useState(true)

    const loadMore = async () => {
        if(posts.length >= data.count) {
            setHasMore(false);
            return false
        }
        await setCurrentPage(currentPage = currentPage + 1);
        let res = await fetch(`http://localhost:7000/api/gallery?limit=12&page=${currentPage}`)
        res = await res.json()
        setPosts([...posts, ...res.rows])
    }

  return (
    <>
      <Head>
        <title>Infinite Scroll - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-[#fff] p-10'>
        <h1 className='text-4xl text-center font-bold mb-10'>Gallery - <span className='text-green-500'>Infinite Scroll</span></h1>
          <InfiniteScroll next={loadMore} hasMore={hasMore} endMessage={<h1 className='text-white-500 text-3xl text-center'>This is the end of scroll!</h1>} loader={<Preloader/>} dataLength={posts.length} className='flex flex-wrap justify-between gap-10'>
                {posts.map(i=><Post item={i} key={i.id}/>)}
            </InfiniteScroll>
      </main>
    </>
  )
}
